backend/package-lock.json
backend/package.json
bot/package-lock.json
bot/package.json
frontend/package-lock.json

**WHY**
The dependabot found some vulnerabilities it could not resolve. This fixes those.
**WHAT**
We had some unused dependency artifacts that are removed here. Also updated express minor to fix security vulnerability.

build(deps): updated unused and stale deps

---

backend/src/app.ts
backend/src/assets/index.html
backend/src/assets/meal-rankings.html
backend/src/assets/optimal-sets.html
backend/src/assets/pokemon-flexible.html
backend/src/assets/pokemon-focused.html
backend/src/assets/production-calculator.html
backend/src/assets/tier-lists.html

**WHY**
The more standardized way of referring to landing html is index.html.
**WHAT**
Renamed landing html from home to index.

feat(frontend): rename home.html to index.html

---

DEVELOPMENT_SETUP.md
backend/README.md
sleepapi.code-workspace

I wrote down a couple of things as I was setting up the development environment on my Windows machine.
Let me know if my commits are too small - we're quite zealous with "only one change per commit" at my work!

Update documentation for Windows development

---

backend/src/assets/index.html
backend/src/assets/meal-rankings.html
backend/src/assets/optimal-sets.html
backend/src/assets/pokemon-flexible.html
backend/src/assets/pokemon-focused.html
backend/src/assets/production-calculator.html
backend/src/assets/tier-lists.html

This commit updates the footer in the simplistic frontend HTML files to include a contribution notice. The notice encourages users to check out the Sleep API on GitHub to contribute to the project.

chore: add contribution notice with GitHub link

---

backend/src/assets/optimal-sets.html
backend/src/assets/production-calculator.html

**WHY**
Different pages had different sized submit buttons. Production calculator had the submit button overlap with the footer when pushed down.
**WHAT**
Aligned submit buttons across pages. Added margin to footer. Moved select recipe above settings for optimal set as the recipe is most important. Rephrased settings to optional for optimal set.
Fixes #41

fix(frontend): submit buttons aligned

---

backend/src/services/calculator/stats/stats-calculator.test.ts
backend/src/services/calculator/stats/stats-calculator.ts
backend/src/services/routing-service/optimal-ranking.ts

fix: limit optimal-set sub-skills for level

---

backend/src/assets/index.html
backend/src/assets/meal-rankings.html
backend/src/assets/optimal-sets.html
backend/src/assets/pokemon-flexible.html
backend/src/assets/pokemon-focused.html
backend/src/assets/production-calculator.html
backend/src/assets/tier-lists.html

**WHY**
What started as encoding issue in optimal-sets.html. Spiraled into having the HTML files be compliant with W3C spec using https://validator.w3.org/ This also introduces integrity check for external resources more info: https://www.srihash.org/ Reordered scripts and style
**WHAT**
Add integrity check for external resources
Fix encoding in optimal-sets.html
Fix compliant with W3C standard
Fix input label

style(frontend): format html to comply with W3C standard

---

backend/src/assets/functions.js
backend/src/assets/index.html
backend/src/assets/meal-rankings.html
backend/src/assets/pokemon-flexible.html
backend/src/assets/pokemon-focused.html
backend/src/assets/production-calculator.html
backend/src/assets/team-finder.html
backend/src/assets/tier-lists.html
backend/src/controllers/optimal/optimal.controller.ts
backend/src/domain/combination/combination.ts
backend/src/public/swagger.json
backend/src/routes/optimal-router/optimal-router.ts
backend/src/services/api-service/optimal/optimal-service.test.ts
backend/src/services/api-service/optimal/optimal-service.ts
backend/src/services/calculator/ingredient/ingredient-calculate.test.ts
backend/src/services/calculator/ingredient/ingredient-calculate.ts
backend/src/services/csv-converter/csv-converter-service.ts
backend/src/services/set-cover/set-cover.test.ts
backend/src/services/set-cover/set-cover.ts

**WHY**
The name of the tool "Optimal Set" was confusing and explained
more about the algorithm behind it than it did what the tool is
actually to be used for.
We were missing description of the tool.
We had no direct selection of subskills.
**WHAT**
Renamed Optimal Set to Team finder.
Added detailed description of the tool, with assumptions and some
information about the algorithm behind it.
Added selection of subskills with default to optimal.

feat(teamfinder): improved Optimal Set settings

---

.github/ISSUE_TEMPLATE/bug.yml
DEVELOPMENT_SETUP.md
README.md
backend/README.md
backend/src/domain/combination/combination.ts
backend/src/public/swagger.json
backend/src/services/api-service/optimal/optimal-service.test.ts
backend/src/services/calculator/ingredient/ingredient-calculate.test.ts
backend/src/services/calculator/ingredient/ingredient-calculate.ts
backend/src/services/csv-converter/csv-converter-service.ts
backend/src/services/set-cover/set-cover.test.ts
backend/src/services/set-cover/set-cover.ts
backend/src/services/website-converter/website-converter-service.ts
bot/README.md
frontend/README.md

updated docs to reflect new environment instead of azure

feat(teamfinder): replace produce with surplus in details

---

backend/src/assets/404.html
backend/src/assets/global.css

feat: add a 404 page

---

backend/src/controllers/calculator/production.controller.ts
frontend/src/components/account/account-menu.vue
frontend/src/components/calculator/team-name.test.ts
frontend/src/components/calculator/team-name.vue
frontend/src/components/calculator/team-settings.test.ts
frontend/src/components/calculator/team-settings.vue
frontend/src/components/calculator/team-slot.vue
frontend/src/stores/team/team-store.test.ts
frontend/src/stores/team/team-store.ts

fix: team name no longer cached when windowing

fix: inventory subskills now add carry size correctly

---

backend/src/public/swagger.json
backend/src/services/simulation-service/team-simulator/member-state.test.ts
backend/src/services/simulation-service/team-simulator/team-simulator-utils.test.ts
backend/src/services/simulation-service/team-simulator/team-simulator.test.ts
backend/src/utils/test-utils/defaults.ts
common/src/domain/pokemon/berry-pokemon.ts
common/src/domain/pokemon/ingredient-pokemon.ts
common/src/domain/pokemon/pokemon.test.ts
common/src/domain/pokemon/pokemon.ts
common/src/domain/pokemon/skill-pokemon.ts
common/src/utils/pokemon-utils/evolution-utils.test.ts
common/src/utils/pokemon-utils/evolution-utils.ts
common/src/utils/pokemon-utils/index.ts

Add remaining evolutions

---

backend/src/services/calculator/skill/activation/__snapshots__/skill-activation.test.ts.snap
common/src/domain/ingredient/ingredient.ts

Soothing Cacao -> Rousing Coffee

fix: coffee longName

---

LICENSE

The LICENSE file has placeholders from the template added in the initial commit. Add current year and attribute copyright ownership to Neroli's Lab Team.

Add name and date to LICENSE

---

frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/vite.config.ts
package-lock.json

Content-Security-Policy is achieved by using `vite-plugin-csp-guard` from https://vite-csp.tsotne.co.uk/

chore: Add Content-Security-Policy and Goatcounter analytics

---

.gitattributes

I'm not 100% convinced this works. I'm seeing some weirdness still on my machine, but at least Git and Jujutsu finally agree as to whether every file has changes. Hopefully, after this submits, I'll stop encountering issues. If I still see issues, they're probably coming from somewhere other than Git-for-Windows, so I'll have to look for other sources.

Add .gitattributes to force LF on Windows

---

frontend/src/components/settings/site-settings/site-settings.vue

Shows a snackbar message to you when the cache is cleared successfully.
This provides you feedback for the clear cache action in the site settings.

feat: show snackbar on cache clear

---

CLAUDE.md
frontend/src/assets/common.scss
frontend/src/components/custom-components/custom-chip/CustomChip.test.ts
frontend/src/components/custom-components/custom-chip/CustomChip.vue
frontend/src/components/tierlist/PokemonDetailModal.vue
frontend/src/components/tierlist/tabs/RecipesTab.test.ts
frontend/src/components/tierlist/tabs/RecipesTab.vue
frontend/src/components/tierlist/tabs/VariantsTab.test.ts
frontend/src/components/tierlist/tabs/VariantsTab.vue
frontend/src/composables/use-sticky-avatar/use-sticky-avatar.test.ts
frontend/src/composables/use-sticky-avatar/use-sticky-avatar.ts

- Fix broken caching in VariantsTab by moving cache Maps outside computed
- Add interactive CustomChip functionality tests for RecipesTab (8 new tests)
- Add comprehensive VariantsTab tests including caching verification (15 tests)
- Fix TypeScript errors by using correct CustomChip props (isSelected vs variant)
- Update CLAUDE.md with commitlint requirements and testing guidelines

style(tierlist): improve variants and recipes tab design and caching

---

.gitignore
backend/package.json
backend/src/config/file-paths.test.ts
backend/src/services/simulation-service/team-simulator/member-state/member-state.test.ts
backend/src/services/simulation-service/team-simulator/member-state/member-state.ts
backend/src/services/simulation-service/team-simulator/team-simulator-benchmark.test.ts
backend/src/services/simulation-service/team-simulator/team-simulator.test.ts
backend/src/vitest/mocks/team/mock-member-production.ts
common/src/types/team/team-calculate.ts
frontend/src/vitest/mocks/calculator/member-production.ts

I added these two tests to make sure my refactor (in preparation for sneaky snacking) didn't break anything and doesn't take noticeably longer.

Add benchmarking tests

---

backend/package-lock.json
backend/src/services/calculator/skill/activation/__snapshots__/skill-activation.test.ts.snap
common/package-lock.json
common/src/types/mainskill/mainskills/ingredient-magnet-s-plus.ts
frontend/package-lock.json
frontend/src/components/pokemon-input/mainskill-button.test.ts
frontend/src/components/pokemon-input/mainskill-button.vue

Previously the amount would always be 0 and the ingredient undefined. This was because ingredient information was not passed in.

fix(Plus skill): description shows amount and ingredient
